### ISSUE TITLE
Need Junit/Integration tests

### ISSUE THREAD

**Issue by jalpp** [jalpp/Chesslise#39]
need test cases for each command

**Comment by halfwind22** [comment]
Would like to take this up, but before that, is there a reason why the package names Abstraction, Chesscom are in uppercase?

**Comment by jalpp** [comment]
> Would like to take this up, but before that, is there a reason why the package names Abstraction, Chesscom are in uppercase?

thanks, no real reason, just so its easy on eyes

**Comment by jalpp** [comment]
@halfwind22 any updates on this? I have updated the project, and unit/integration tests might also need to cover new updates

**Comment by jalpp** [comment]
closing this as I never received a PR for this
