### ISSUE TITLE
Legal move shown as illegal

### ISSUE THREAD

**Issue by ThomasKaputa** [jalpp/Chesslise#59]
**Describe the bug**
The bot tells me that a move is illegal though it's the solution.

**To Reproduce**
1. Added the bot to a private discord server over the Discord app directory
2. /puzzle pick-puzzle Chess.com daily puzzle pick-mode solve it live! (05. June. 2024)
3. wait till image is there
4. /solve Qxh3+

**Expected behavior**
Should show that I entered the right move. But it either shows:

That the bot doesn't react
The move is illegal

**Screenshots**
![image](https://github.com/jalpp/Chesslise/assets/54510958/491e50f7-c46d-4d52-96f1-bd6f3e05eb31)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**
just wanted to play around a little bit with the bot. Something wrong with my steps?

**Comment by jalpp** [comment]
> **Describe the bug** The bot tells me that a move is illegal though it's the solution.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Added the bot to a private discord server over the Discord app directory
> 
>     2. /puzzle pick-puzzle Chess.com daily puzzle pick-mode solve it live! (05. June. 2024)
> 
>     3. wait till image is there
> 
>     4. /solve Qxh3+
> 
> 
> **Expected behavior** Should show that I entered the right move. But it either shows:
> 
> That the bot doesn't react The move is illegal
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/54510958/336996717-491e50f7-c46d-4d52-96f1-bd6f3e05eb31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MjA1NTIsIm5iZiI6MTcxNzYyMDI1MiwicGF0aCI6Ii81NDUxMDk1OC8zMzY5OTY3MTctNDkxZTUwZjctYzQ2ZC00ZDUyLTk2ZjEtYmQ2ZjNlMDVlYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDIwNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmM5YzVkNWE1NzY5MTRiZDE3ZTI1ZmI4MTJmNmYwZjkxYTQwNjM2NWNkYzI1N2JkMDc1YzdhOTQzNjJiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPEEHlM9TkBd_7_ia6kyqjQ5WKJQ1RBpimM6D91-p2I)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: macOS
> 
>     * Browser Chrome
> 
> 
> **Additional context** just wanted to play around a little bit with the bot. Something wrong with my steps?

Hello, thanks for reporting this, Its a known bug actually, but it's not really related to Lise, but rather Stockfish rest API
https://stockfish.online/ Sometimes the servers are working fine there, and sometimes they are not resulting in Lise breaking, I actually started working on my own Stockfish API to support Lise here  https://github.com/jalpp/stockfish-rest-api but I been busy and not been able to get to it and eventually host it. I can change the warning message, and possible fix the Lichess version, but Chess.com one highly relies on the Stockfish rest server that we are not really responsible to maintain

**Comment by jalpp** [comment]
@ThomasKaputa this is partially fixed but as this was about wrong warning messages closing this, if you encounter something similar feel free to open one again!
