### ISSUE TITLE
Feat: Implement failover logic for Daily Lichess puzzle /solve and /puzzle

### ISSUE THREAD

**Issue by jalpp** [jalpp/Chesslise#61]
usually the puzzle /solve fails because Stockfish API is not that stable. Still, the Lichess daily puzzle automatically answers the puzzle of the daily puzzle which doesn't need stockfish API. We want to implement a failover whenever the stockfish API is not working for the Lichess daily puzzle, we resort to the Lichess daily puzzle endpoint for answers and keep on triggering the puzzle trigger module until the user solves it.

docs: https://lichess.org/api#tag/Puzzles/operation/apiPuzzleDaily

classes that need work PuzzleSolverContextModule Lichess daily puzzle logic already present in Lichess/DailyCommand

opening this good first issue, because it's easy if you look deep and I'm really busy nowadays

**Comment by subhashree9898** [comment]
@jalpp please assign this issue to me

**Comment by jalpp** [comment]
if your stuck feel free to join the Discord, otherwise its quite straightforward task

**Comment by jalpp** [comment]
any updates? @subhashree9898

**Comment by jalpp** [comment]
6909a015782a41c48a0c75a984210fb7f5d7d51d
