### ISSUE TITLE
Feat: cool image background profile card for Lichess and Chess.com

### ISSUE THREAD

**Issue by jalpp** [jalpp/Chesslise#62]
the current commands /profile and /profilecc cards only show embeds and the data doesn't look well 

would like a card for both that looks something like this

![Screen Shot 2024-06-17 at 2 13 16 PM](https://github.com/jalpp/Chesslise/assets/92553013/83062dfb-1178-44e1-b578-cdadb4a1c2d4)

not the same, but it is something to take inspiration from, the code for generating profile cards is already present in Profile.java and ProfileCC.java

I am opening this to everyone, a good first issue for everyone to come up with a cool design!

**Comment by nicvagn** [comment]
kk, neat.  I am a bit busy atm, but I will give it a look when I get a chance

Thanks for thinking of me

**Comment by nicvagn** [comment]
![image](https://github.com/jalpp/Chesslise/assets/37600758/49211ba8-23af-4544-b854-70729418db36)
I do not have the graphics design to do better than this lol. 

There is a reason NicLink is cli xD

**Comment by jalpp** [comment]
haha yea truly open to everyone and their creative ideas!

**Comment by jalpp** [comment]
@cnunezre is interested

**Comment by jalpp** [comment]
any updates @cnunezre

**Comment by cnunezre** [comment]
@jalpp I was looking at this the other day - I think what ChessBot is showing is an image. I have not use it so I haven't seen the example. I haven't had much time lately but still interested in doing it. Let's DM in discord.

**Comment by jalpp** [comment]
6909a015782a41c48a0c75a984210fb7f5d7d51d

**Comment by nicvagn** [comment]
sad pepe.
